USE [master]
GO

/****** Object:  Database [axosnet]    Script Date: 15/01/2022 11:49:07 a. m. ******/
CREATE DATABASE [axosnet]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'axosnet', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\axosnet.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'axosnet_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\axosnet_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [axosnet].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [axosnet] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [axosnet] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [axosnet] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [axosnet] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [axosnet] SET ARITHABORT OFF 
GO

ALTER DATABASE [axosnet] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [axosnet] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [axosnet] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [axosnet] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [axosnet] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [axosnet] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [axosnet] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [axosnet] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [axosnet] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [axosnet] SET  DISABLE_BROKER 
GO

ALTER DATABASE [axosnet] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [axosnet] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [axosnet] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [axosnet] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [axosnet] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [axosnet] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [axosnet] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [axosnet] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [axosnet] SET  MULTI_USER 
GO

ALTER DATABASE [axosnet] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [axosnet] SET DB_CHAINING OFF 
GO

ALTER DATABASE [axosnet] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [axosnet] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [axosnet] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [axosnet] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [axosnet] SET QUERY_STORE = OFF
GO

ALTER DATABASE [axosnet] SET  READ_WRITE 
GO


